### ISSUE TITLE
Running Redis UI on a subdirectory

### ISSUE THREAD

**Issue by vojtechzicha** [patrikx3/redis-ui#43]
Hi,

I've tried deploying Redis UI to Kubernetes Ingress and I've stumbled upon an issue running on non-root path.

When published via following definition:

```
- path: /redis/(.*)
  backend:
    serviceName: redis-ui                                                                                                        
    servicePort: 7843
```

The application loads on `https://example.com/redis/`, but the JS and page itself still loads as `https://example.com/bundle.js`.

Usually in similar docker apps, there is an environment variable that can provide the path, but I cannot find any in this project.

Is there a way to run the app on non-root path?

If there is a hint where to do the change in code, I can try doing pull request but haven't find the right place, so any hints would be welcomed too.

**Comment by sergeyshaykhullin** [comment]
@vojtechzicha If you use ingress-ngins you can use it to rewrite urls on routing

You have to add annotation to ingress
```yaml
nginx.ingress.kubernetes.io/rewrite-target: /$2
```

And create path like this
```yaml
- path: /myroute(/|$)(.*)
  backend:
    serviceName: myservice
    servicePort: http
```

Nginx will receive `/myroute` routes, rewrite them as they are `/` and pass to specified service

**Comment by f2calv** [comment]
I can't get rewrite working, its been a while since I touched HTML but I think setting base href is the cause;
```html
<base href="/">
```

**Comment by f2calv** [comment]
So it's now working just _not_ using rewrite below is my solution for next `customer`!
Note: I'm using Lets Encrypt TLS termination in my example;

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisui-ingress
  labels:
    app: redisui-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /redis
spec:
  tls:
    - hosts:
        - www.example.com
      secretName: tls-secret-redisui
  rules:
    - host: www.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redisui-svc
                port:
                  number: 7843
```
Official rewrite docs;
- https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md
