### ISSUE TITLE
k8s chart ingress is old

### ISSUE THREAD

**Issue by eyalzamir** [patrikx3/redis-ui#86]
I had updated the ingress to a non beta release version 

ingress.yaml
=========
```
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: p3x-redis-ui-ingress
  labels:
    app: p3x-redis-ui
    chart: p3x-redis-ui
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{- range .Values.ingress.tls }}
    - hosts:
{{- range .hosts }}
        - {{ . | quote }}
{{- end }}
      secretName: {{ .secretName }}
{{- end }}
{{- end }}
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
{{- if .Values.ingress.enabled }}
{{- $uiPath := .Values.ingress.path -}}
{{- $uiPort := .Values.ingress.service.port -}}
{{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $uiPath }}
            pathType: Prefix
            backend:
              service:
                name: p3x-redis-ui-service
                port:
                  number: {{ $uiPort }}
{{- end }}
{{- end }}
{{- end }}

```

here is the updated values.yaml
===============

```

image:
    repository: patrikx3/p3x-redis-ui
    tag: latest
    pullPolicy: Always

license:

replicas: 1

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 100M
  # limits:
  #   cpu: 200m
#   memory: 200M

connections:
 - name: daas-cache-kryon-dev.ptdwzp.0001.euc1.cache.amazonaws.com
   host: daas-cache-kryon-dev.ptdwzp.0001.euc1.cache.amazonaws.com
   port: 6379
   id: 1
   password:
   azure: false
   cluster: false
   awsElastiCache: true

service:
    type: ClusterIP
#  nodePort: 30200 If type is NodePort

ingress:
  enabled: true
  service:
    port: 7843
  annotations: {}
  path: /
  hosts:
    - cache.example.com
  className: nginx-pd-release
  tls:
    - hosts:
        - "cache.example.com"
      secretName: example.com-tls


nodeSelector: {}

```
